### ISSUE TITLE
Why R ggplot2 over Vega-Lite or XChart

### ISSUE THREAD

**Issue by ValdarT** [holgerbrandl/kravis#21]
Hi

Thank you for your work on the data science tooling in Kotlin! 

I see you implemented experimental backends for Vega-Lite and XCharts, too, but decided to stay with calling R and ggplot2. I'm curious what was the reason for this, because, at first sight, this seems the least optimal due to introducing the dependency on R and missing out on the interactiveness of Vega?

**Comment by holgerbrandl** [comment]
I was just way more familiar with ggplott compared to vega. Everyone lives in a bubble, and mine was more ggplot. 

The dependency on R is not pretty I agree, in particular, since it does not seem possible to bundle R in a jar. Still, ggplot is superior to any other scientific visualization package I know. That's why I think it's worth the compromise.
